version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: gamehub-postgres
    environment:
      POSTGRES_DB: gamehub
      POSTGRES_USER: gamehub
      POSTGRES_PASSWORD: gamehub
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
